# INTRO TO PANDAS

* RESOURCE: https://www.youtube.com/watch?v=sZDgJKI8DAM
* NOTION NOTES:  https://www.notion.so/Python-for-Data-Analysts-185903ebc850452abb81fae7049661e8

In [2]:
import pandas as pd
import os

pwd = os.getcwd()


netflix = pd.read_csv(pwd + "/netflix_titles.csv")
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [4]:
list(netflix.columns)

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description']

In [6]:
netflix.describe()

       release_year
count   7787.000000
mean    2013.932580
std        8.757395
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2018.000000
max     2021.000000

In [16]:
# perceber quais sao ao valores unicos num dataframe
# netflix aqui neste caso é considerado o nosso data frame

netflix['type'].unique()
netflix['country'].unique()

array(['Brazil', 'Mexico', 'Singapore', 'United States', 'Turkey',
       'Egypt', 'India', 'Poland, United States', 'Thailand', 'Nigeria',
       nan, 'Norway, Iceland, United States', 'United Kingdom', 'Japan',
       'South Korea', 'Italy', 'Canada', 'Indonesia', 'Romania', 'Spain',
       'Iceland', 'South Africa, Nigeria', 'France',
       'United States, South Africa', 'Portugal, Spain',
       'Hong Kong, China, Singapore', 'United States, Germany',
       'South Africa, China, United States', 'Argentina',
       'United States, France, Serbia', 'Germany',
       'Denmark, France, Poland', 'Poland', 'Kenya',
       'New Zealand, United Kingdom', 'Pakistan', 'Australia',
       'Australia, United States', 'Mexico, United States',
       'United States, China', 'China, Hong Kong', 'Taiwan',
       'United States, United Kingdom', 'France, South Korea, Japan',
       'United States, Canada', 'United Kingdom, United States',
       'Netherlands, Denmark, South Africa', 'Canada, United States',
       'Denmark', 'Hong Kong', 'France, Netherlands, Singapore', 'China',
       'Philippines', 'United Kingdom, Spain, United States',
       'United Arab Emirates, United States', 'Netherlands',
       'United Kingdom, Hong Kong', 'Iran, France',
       'United States, United Kingdom, France',
       'United Kingdom, France, Belgium, United States, China',
       'Argentina, Brazil, France, Poland, Germany, Denmark',
       'Israel, United States', 'United States, Mexico',
       'Uruguay, Argentina, Spain', 'Singapore, France',
       'United Kingdom, United States, France, Germany',
       'Turkey, United States', 'Bulgaria, United States',
       'Australia, France', 'Hong Kong, Iceland, United States',
       'United Arab Emirates', 'United States, Chile',
       'Germany, France, Russia', 'Mauritius, South Africa',
       'United States, Japan', 'Lebanon', 'United States, Bulgaria',
       'Colombia', 'Uruguay, Argentina', 'Egypt, Algeria',
       'France, Egypt', 'Uruguay', 'Soviet Union, India',
       'Sweden, United States', 'South Africa', 'Malaysia',
       'Ireland, United Kingdom, United States', 'Spain, Italy',
       'United Kingdom, France, Germany',
       'United States, Germany, Canada', 'United States, India',
       'Japan, United States', 'Denmark, United States',
       'South Africa, United States', 'Canada, Luxembourg',
       'Serbia, United States', 'Canada, Nigeria',
       'Iceland, Sweden, Belgium', 'Ireland, Canada',
       'United States, Italy', 'Finland', 'India, Germany',
       'China, Spain, South Korea, United States', 'Spain, Belgium',
       'United Kingdom, Canada, United States, Germany',
       'Brazil, Netherlands, United States, Colombia, Austria, Germany',
       'France, Canada, Belgium',
       'India, United Kingdom, China, Canada, Japan, South Korea, United States',
       'France, Belgium', 'Indonesia, South Korea, Singapore', 'Norway',
       'Peru', 'France, Senegal, Belgium', 'Canada, France', 'Chile',
       'Romania, France, Switzerland, Germany',
       'Bulgaria, United States, Spain, Canada', 'Sweden, Netherlands',
       'Ghana', 'France, United States, Mexico',
       'Australia, United Kingdom, United Arab Emirates, Canada',
       'Singapore, United States', 'Japan, Canada, United States',
       'Saudi Arabia',
       'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay',
       'United States, France', 'Norway, Denmark, Netherlands, Sweden',
       'Namibia', 'Mexico, Finland', 'United States, Australia', 'Russia',
       'Australia, Canada', 'United Kingdom, Ireland', 'Belgium, France',
       'New Zealand', 'Uruguay, Spain, Mexico', 'South Korea, China',
       'United States, Canada, Indonesia, United Kingdom, China, Singapore',
       'India, Iran', 'United States, France, Japan',
       'United Kingdom, France', 'Turkey, India', 'Philippines, Qatar',
       'Vietnam', 'Ireland, Luxembourg, Belgium',
       'Saudi Arabia, Syria, Egypt, Lebanon, Kuwait',
       'Russia, United States', 'United Kingdom, Russia, United States',
       'Argentina, Spain', 'Germany, Jordan, Netherlands',
       'Hong Kong, China', 'Argentina, United States',
       'France, Belgium, Spain', 'Germany, United States',
       'Denmark, Sweden, Israel, United States',
       'Ireland, United Kingdom', 'United States, Iceland',
       'United Arab Emirates, United Kingdom, India', 'Sweden',
       'Norway, Germany, Sweden', 'Finland, France', 'Denmark, Spain',
       'United Kingdom, Russia',
       'United States, United Kingdom, Australia',
       'India, United Kingdom', 'United States, Canada, Ireland',
       'Canada, United Kingdom',
       'United States, Israel, Italy, South Africa',
       'India, United States', 'United Kingdom, China',
       'Indonesia, Singapore', 'Netherlands, Denmark, France, Germany',
       'South Korea, Japan',
       'Philippines, Canada, United Kingdom, United States',
       'France, Malta, United States', 'Kuwait',
       'United Kingdom, Pakistan', 'Ireland', 'France, New Zealand',
       'United Kingdom, United States, Australia',
       'United Kingdom, Czech Republic, United States, Germany, Bahamas',
       'United States, Australia, China',
       'China, Germany, India, United States', 'Germany, Sri Lanka',
       'United States, Sweden', 'Canada, United States, Cayman Islands',
       'India, France', 'United Kingdom, Canada',
       'United States, India, Bangladesh',
       'United States, Canada, France',
       'Taiwan, China, France, United States', 'Brazil, France, Germany',
       'United States,', 'Turkey, France, Germany, Poland',
       'Australia, New Zealand, United States',
       'Germany, United States, Hong Kong, Singapore',
       'France, Germany, Switzerland', 'Mexico, Argentina',
       'Italy, United States, Argentina',
       'Germany, France, Luxembourg, United Kingdom, United States',
       'Canada, United States, United Kingdom',
       'United Kingdom, Canada, Italy', 'Czech Republic, France',
       'Zimbabwe', 'United Kingdom, France, Germany, Spain',
       'Taiwan, Hong Kong, United States, China', 'China, United States',
       'Canada, Brazil', 'United Kingdom, Australia', 'Hungary',
       'Germany, Australia', 'United Kingdom, Poland, United States',
       'Bulgaria', 'Philippines, United States', 'Finland, Germany',
       'United States, Thailand',
       'Spain, Belgium, Switzerland, United States, China, United Kingdom',
       'Denmark, Zimbabwe', 'United Kingdom, South Africa',
       'Finland, Sweden, Norway, Latvia, Germany',
       'United Kingdom, India',
       'South Africa, United States, New Zealand, Canada',
       'France, Qatar', 'France, Algeria',
       'United States, Italy, United Kingdom, Liechtenstein',
       'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom',
       'United States, Australia, Mexico',
       'United Kingdom, Czech Republic, Germany, United States',
       'Russia, Poland, Serbia', 'France, China, Japan, United States',
       'United States, South Korea, China', 'Germany, Belgium',
       'Chile, Argentina', 'China, United States, United Kingdom',
       'Pakistan, Norway, United States',
       'United Kingdom, Japan, United States', 'Philippines, Singapore',
       'United States, Canada, Belgium, United Kingdom', 'Venezuela',
       'Argentina, Uruguay, Serbia', 'United States, Mexico, Colombia',
       'Colombia, Peru, United Kingdom', 'Brazil, United States',
       'Czech Republic, United States',
       'Canada, France, Italy, Morocco, United States',
       'Canada, Spain, France', 'Hong Kong, United States',
       'France, Canada, China, Cambodia', 'United States, Indonesia',
       'Spain, France', 'Spain, Mexico, France', 'Spain, France, Italy',
       'Spain, France, United States', 'United States, France, Canada',
       'Israel', 'Italy, France', 'United Kingdom, Canada, United States',
       'Cambodia, United States', 'China, Japan',
       'United Arab Emirates, United States, United Kingdom',
       'Argentina, Italy', 'United Kingdom, Israel, Russia',
       'Italy, Switzerland, Albania, Poland', 'Spain, Cuba',
       'United States, Brazil', 'United States, France, Mexico',
       'United States, Nicaragua', 'Austria, Germany',
       'United Arab Emirates, Jordan, Lebanon',
       'France, United Kingdom, United States',
       'United Kingdom, United States, Spain, Germany, Greece, Canada',
       'France, Belgium, Luxembourg, Cambodia,', 'Italy, Turkey',
       'Brazil, France', 'India, Turkey', 'Kenya, United States',
       'United States, South Korea', 'South Korea, United States',
       'Italy, Canada, France', 'Thailand, United States',
       'United Kingdom, Denmark, Canada, Croatia', 'Netherlands, Belgium',
       'United Kingdom, Canada, United States, Cayman Islands',
       'Italy, Germany', 'United States, France, United Kingdom, Japan',
       'United States, United Kingdom, Denmark, Sweden',
       'United States, United Kingdom, Italy',
       'United States, France, Canada, Spain', 'Uruguay, Guatemala',
       'Germany, Australia, France, China',
       'United States, United Kingdom, Japan',
       'United States, United Kingdom, Canada',
       'Italy, Switzerland, France, Germany',
       'Russia, United States, China', 'United States, Canada, Germany',
       'United States, Czech Republic', 'Ireland, United States',
       'United States, United Arab Emirates',
       'France, Australia, Germany', 'Hong Kong, China, United States',
       'Lebanon, United Arab Emirates, France, Switzerland, Germany',
       'United States, South Korea, Japan', 'Romania, United States',
       'West Germany', 'United States, Ireland', 'Chile, Italy',
       'Ireland, United Kingdom, Italy, United States', 'Belgium',
       'Poland,', 'Slovenia, Croatia, Germany, Czech Republic, Qatar',
       'Canada, United Kingdom, Netherlands',
       'United Kingdom, United States, France',
       'Indonesia, United Kingdom', 'United States, Spain, Germany',
       'India, Japan', 'Switzerland, France, Belgium, United States',
       'China, South Korea, United States',
       'United Kingdom, France, Belgium',
       'Canada, Ireland, United States',
       'United Kingdom, United States, Dominican Republic',
       'United States, Senegal', 'Germany, United Kingdom, United States',
       'United States, Canada, United Kingdom',
       'Canada, United States, France', 'United Kingdom, Germany, Canada',
       'Argentina, France', 'South Africa, Germany, Netherlands, France',
       'Canada, United States, United Kingdom, France, Luxembourg',
       'Finland, Germany, Belgium',
       'United States, United Kingdom, Germany', 'Taiwan, China',
       'Cambodia', 'Spain, Portugal', 'Ireland, United States, France',
       'Jordan', 'Austria', 'Germany, United States, Canada',
       'United Kingdom, Germany, Canada, United States',
       'United States, France, Canada, Lebanon, Qatar',
       'Indonesia, Netherlands',
       'Netherlands, Belgium, United Kingdom, United States',
       'China, United States, Australia',
       'France, Belgium, China, United States', 'Spain, United Kingdom',
       'United States, Chile, Israel', 'Bangladesh',
       'United Kingdom, Norway, Denmark, Germany, Sweden',
       'United States, Japan, Canada', 'Norway, Denmark, Sweden',
       'China, India, Nepal', 'United States, Argentina',
       'Mexico, United States, Spain, Colombia',
       'Colombia, Mexico, United States',
       'United Kingdom, Belgium, Sweden', 'Nigeria, United Kingdom',
       'United Kingdom, South Korea', 'United States, Taiwan',
       'Netherlands, Belgium, Germany, Jordan', 'France, Canada',
       'United Kingdom, France, United States',
       'Denmark, Singapore, Canada, United States', 'Denmark, China',
       'Malaysia, Singapore, Hong Kong', 'Norway, United States',
       'United States, Philippines', 'United States, Greece, Brazil',
       'France, United States', 'South Korea, France',
       'United States, Australia, Samoa, United Kingdom',
       'Canada, South Africa', 'United Kingdom, Italy',
       'Germany, United Kingdom', 'China, United Kingdom',
       'Argentina, Chile, Peru', 'United States, Russia',
       'Uruguay, Germany', 'Turkey, Azerbaijan',
       'United States, China, Hong Kong',
       'Canada, Germany, France, United States',
       'Argentina, United States, Mexico',
       'France, United Kingdom, India', 'China, Taiwan',
       'Italy, United Kingdom, France', 'Poland, West Germany',
       'Germany, United States, Sweden', 'Canada, Spain',
       'United Kingdom, France, Belgium, United States', 'France, Japan',
       'Netherlands, Germany, Italy, Canada', 'United States, Cambodia',
       'United States, Greece', 'United States, China, Colombia',
       'United States, Spain, Italy',
       'Norway, United Kingdom, France, Ireland',
       'United States, Bermuda, Ecuador', 'United Kingdom, Poland',
       'China, Canada, United States', 'United States, Spain',
       'India, Mexico', 'United Kingdom, West Germany',
       'Pakistan, United States', 'Israel, Sweden, Germany, Netherlands',
       'Chile, United States, France', 'France, Morocco',
       'United Kingdom, Germany', 'Georgia, Germany, France',
       'Switzerland, France', 'Turkey, South Korea', 'Italy, India',
       'United States, Botswana', 'United States, Colombia, Mexico',
       'Chile, Argentina, France, Spain, United States',
       'Puerto Rico, United States, Colombia', 'United States, Nigeria',
       'Germany, United States, France',
       'Spain, Germany, Denmark, United States',
       'United Kingdom, United States, Japan',
       'Netherlands, United States',
       'United States, India, South Korea, China',
       'Denmark, Germany, Belgium, United Kingdom, France',
       'Denmark, Germany, Belgium, United Kingdom, France, Sweden',
       'France, Switzerland, Spain, United States, United Arab Emirates',
       'Norway, Sweden', 'United States, Ireland, United Kingdom, India',
       'United Kingdom, Singapore', 'Spain, Germany',
       'Germany, Czech Republic',
       'Denmark, Brazil, France, Portugal, Sweden',
       'Brazil, India, China, United States', 'India, Germany, Austria',
       'Italy, United States', 'Denmark, France, United States, Sweden',
       'Australia, Iraq', 'China, Morocco, Hong Kong', 'Spain, Colombia',
       'Australia, United Arab Emirates',
       'Canada, United States, Germany', 'France, Belgium, Italy',
       'United Kingdom, Thailand', 'Venezuela, Colombia',
       'France, Luxembourg, Canada', 'India, Nepal', 'Mexico, Spain',
       'Colombia, United States', 'Colombia, Mexico',
       'France, Germany, Czech Republic, Belgium',
       'Germany, China, United Kingdom', 'Canada, Hungary, United States',
       'Pakistan, United Arab Emirates', 'France, United Kingdom',
       'Spain, United Kingdom, United States', 'United Kingdom, Kenya',
       'United States, Norway, Canada', 'Canada, United States, Ireland',
       'Switzerland, Vatican City, Italy, Germany, France',
       'Portugal, France, Poland, United States',
       'France, Japan, United States', 'United States, New Zealand',
       'United States, New Zealand, Japan',
       'United States, Netherlands, Japan, France', 'India, Switzerland',
       'Canada, India', 'Canada, Japan, United States',
       'United States, Morocco', 'United States, Mexico, Spain, Malta',
       'Norway, Denmark', 'South Korea, Canada, United States, China',
       'Singapore, Japan, France',
       'Canada, Mexico, Germany, South Africa',
       'United Kingdom, United States, Canada',
       'Germany, France, United States, Canada, United Kingdom',
       'Peru, Germany, Norway', 'Singapore, Malaysia',
       'United States, Uruguay', 'India, Canada',
       'Ireland, Canada, United Kingdom, United States',
       'United States, Germany, Australia', 'Senegal',
       'Israel, Germany, France', 'Australia, France, Ireland',
       'South Africa, Angola', 'Austria, Czech Republic',
       'Australia, India', 'United States, United Kingdom, Canada, Japan',
       'Sweden, United Kingdom, Finland', 'Hong Kong, Taiwan',
       'United States, United Kingdom, Spain, South Korea',
       'South Korea, China, United States', 'Guatemala', 'Ukraine',
       'United States, United Kingdom, Canada, China',
       'Italy, South Africa, West Germany, Australia, United States',
       'United Kingdom, Finland, Germany',
       'South Africa, United States, Germany',
       'United States, Germany, United Kingdom, Australia',
       'India, Soviet Union', 'Italy, France, Switzerland',
       'Canada, France, United States', 'United States, Colombia',
       'India, Malaysia', 'Switzerland, United States',
       'Thailand, Canada, United States',
       'China, Hong Kong, United States', 'United Kingdom, New Zealand',
       'United Kingdom, France, Germany, United States',
       'South Korea, Czech Republic',
       'Czech Republic, United Kingdom, France',
       'Australia, United Kingdom, Canada',
       'Canada, United Kingdom, United States', 'United States, Hungary',
       'Jamaica, United States', 'Switzerland',
       'Australia, United Kingdom, United States, New Zealand, Italy, France',
       'France, United States, Canada', 'Australia, United Kingdom',
       'United States, Denmark',
       'United Kingdom, France, Canada, Belgium, United States',
       'Denmark, United Kingdom, Sweden', 'Belarus', 'Cyprus',
       'Lebanon, United States, United Arab Emirates',
       'United States, Hong Kong', 'United States, Kazakhstan',
       'Argentina, France, United States, Germany, Qatar',
       'United States, Germany, United Kingdom',
       'United States, Germany, United Kingdom, Italy',
       'United States, New Zealand, United Kingdom',
       'Finland, United States', 'Spain, France, Uruguay',
       'France, Belgium, United States', 'France, Canada, United States',
       'Spain, Argentina', 'United Kingdom, India, United States',
       'Chile, France',
       'United States, United Kingdom, France, Germany, Japan',
       'Canada, Norway', 'United States, Hungary, Ireland, Canada',
       'United States, Canada, China', 'United Kingdom, Malawi',
       'Ireland, Canada, Luxembourg, United States, United Kingdom, Philippines, India',
       'United States, Czech Republic, United Kingdom',
       'Ghana, United States', 'Israel, Germany', 'Spain, Mexico',
       'Mexico, France', 'Brazil, United Kingdom',
       'France, Belgium, Luxembourg, Romania, Canada, United States',
       'Israel, Germany, Poland, Luxembourg, Belgium, France, United States',
       'France, Germany', 'United States, Malta, France, United Kingdom',
       'United Kingdom, United States, Germany, Denmark, Belgium, Japan',
       'Austria, United States', 'Canada, Australia',
       'Greece, United States',
       'United Kingdom, France, Belgium, Canada, United States',
       'Argentina, Chile', 'Czech Republic, Slovakia',
       'United Kingdom, Germany, United States, France',
       'United Kingdom, Lithuania', 'Egypt, France',
       'Spain, France, Canada', 'United States, Greece, United Kingdom',
       'United Kingdom, China, United States, India', 'Taiwan, Malaysia',
       'United States, Sweden, Norway',
       'United Kingdom, United States, Morocco',
       'United States, United Kingdom, Morocco',
       'United States, China, Canada', 'Spain, Canada, United States',
       'Canada, Belgium', 'United States, India, United Arab Emirates',
       'United Kingdom, Canada, France, United States',
       'Spain, Thailand, United States', 'Canada, Germany, South Africa',
       'India, Germany, France',
       'United States, Israel, United Kingdom, Canada',
       'United Kingdom, Hungary, Australia', 'Lebanon, France',

In [ ]:
#no caso de precisar de filtrar algum campo

netflix[netflix['country'] == 'Singapore']

In [12]:
# no caso de precisar de usar multiplos filtros

netflix[(netflix['country'] == 'Singapore') & (netflix['rating']=="TV-MA")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2093,s2094,Movie,Fakkah Fuzz: Almost Banned,Michael McKay,Fakkah Fuzz,Singapore,"January 26, 2018",2018,TV-MA,61 min,Stand-Up Comedy,Stand-up comic Fakkah Fuzz mines cross-cultura...
2956,s2957,Movie,Imperfect,Steve Cheng,"Edwin Goh, Ian Fang Weijie, Phua Yida, Kimberl...",Singapore,"December 20, 2018",2012,TV-MA,95 min,"Action & Adventure, International Movies","After a brawl lands him in a Boys’ Home, a tee..."
3528,s3529,Movie,Lang Tong,Sam Loh,"William Lawandi, Angeline Yap, Vivienne Tseng,...",Singapore,"December 20, 2018",2015,TV-MA,82 min,"International Movies, Thrillers","After seducing a philandering con man, a rebel..."
4138,s4139,Movie,Miss J Contemplates Her Choice,Jason Lai,"Kit Chan, Xiang Yun, Bobby Tonelli, Shane Pow,...",Singapore,"December 20, 2018",2014,TV-MA,89 min,"Dramas, International Movies, Thrillers",The life of a radio talk-show host is turned u...
6949,s6950,TV Show,The Truth Seekers,NaN,"Chen Hanwei, Rebecca Lim, Desmond Tan, Yusuke ...",Singapore,"July 1, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A veteran cop forms an agency dedicated to sol...

In [13]:
# quando precisamos de usar o ou apenas precisamos de usar um pipe |

netflix[(netflix['country'] == 'Singapore') | (netflix['rating']=="TV-MA")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
5,s6,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,"July 1, 2017",2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...
6,s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,"June 1, 2020",2019,TV-MA,95 min,"Horror Movies, International Movies","After an awful accident, a couple admitted to ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
7779,s7780,TV Show,Zona Rosa,NaN,"Manu NNa, Ana Julia Yeyé, Ray Contreras, Pablo...",Mexico,"November 26, 2019",2019,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...",An assortment of talent takes the stage for a ...
7780,s7781,Movie,Zoo,Shlok Sharma,"Shashank Arora, Shweta Tripathi, Rahul Kumar, ...",India,"July 1, 2018",2018,TV-MA,94 min,"Dramas, Independent Movies, International Movies",A drug dealer starts having doubts about his t...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [20]:
netflix[netflix['country']=='Italy']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
28,s29,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",2019,TV-14,95 min,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol..."
73,s74,Movie,18 Presents,Francesco Amato,"Vittoria Puccini, Benedetta Porcaroli, Edoardo...",Italy,"May 8, 2020",2020,TV-MA,114 min,"Dramas, Independent Movies, International Movies",A pregnant mother with terminal cancer leaves ...
111,s112,TV Show,44 Cats,NaN,"Sarah Natochenny, Suzy Myers, Simona Berman, E...",Italy,"October 1, 2020",2018,TV-Y7,2 Seasons,Kids' TV,Paw-esome tales abound when singing furry frie...
119,s120,Movie,5 Star Christmas,Marco Risi,"Massimo Ghini, Ricky Memphis, Martina Stella, ...",Italy,"December 7, 2018",2018,TV-14,96 min,"Comedies, International Movies",When the Italian prime minister meets his love...
668,s669,TV Show,Baby,NaN,"Benedetta Porcaroli, Alice Pagani, Riccardo Ma...",Italy,"September 16, 2020",2020,TV-MA,3 Seasons,"International TV Shows, TV Dramas, Teen TV Shows","Fed up with their families and classmates, two..."
760,s761,TV Show,Bat Pat,NaN,"Rosa Romay, Alberto Escobal, Jaime de Diego, J...",Italy,"December 31, 2017",2016,TV-Y,1 Season,Kids' TV,A curious and talkative bat finds spooky fun o...
1179,s1180,TV Show,Call Me Francis,NaN,"Rodrigo de la Serna, Sergio Hernández, Mercede...",Italy,"December 16, 2016",2016,TV-14,1 Season,"International TV Shows, Spanish-Language TV Sh...","On his path to becoming Pope Francis, Father J..."
1554,s1555,TV Show,Curon,NaN,"Valeria Bilello, Luca Lionello, Federico Russo...",Italy,"June 10, 2020",2020,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Horror","After 17 years, a woman returns home with her ..."
1926,s1927,Movie,Edoardo Ferrario: Temi Caldi,Francesco Imperato,Edoardo Ferrario,Italy,"March 15, 2019",2019,TV-MA,65 min,Stand-Up Comedy,Italian comedian Edoardo Ferrario riffs on lif...
2034,s2035,Movie,Euphoria,Valeria Golino,"Riccardo Scamarcio, Valerio Mastandrea, Isabel...",Italy,"November 1, 2019",2018,R,110 min,"Dramas, International Movies, LGBTQ Movies",An entrepreneur prone to partying and his estr...
2256,s2257,Movie,Francesco De Carlo: Cose di Questo Mondo,NaN,Francesco De Carlo,Italy,"April 12, 2019",2019,TV-MA,61 min,Stand-Up Comedy,"Taking the stage in Milan, Francesco De Carlo ..."
2540,s2541,Movie,Grillo vs Grillo,NaN,Beppe Grillo,Italy,"February 10, 2017",2017,TV-MA,96 min,Stand-Up Comedy,Outspoken comedian Beppe Grillo reminisces abo...
3489,s3490,Movie,La Coppia dei Campioni,Giulio Base,"Massimo Boldi, Massimiliano Tortora, Anna Mari...",Italy,"February 15, 2017",2016,TV-MA,88 min,"Comedies, International Movies","After winning a shared trip to a soccer match,..."
3817,s3818,TV Show,Luna Nera,NaN,"Antonia Fotaras, Giorgio Belli, Manuela Mandra...",Italy,"January 31, 2020",2020,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...","In 17th-century Italy, a teenager learns about..."
3851,s3852,TV Show,Maggie & Bianca: Fashion Friends,Iginio Straffi,"Emanuela Rei, Giorgia Boni, Sergio Ruggeri, Lu...",Italy,"March 31, 2019",2017,TV-Y7,1 Season,"Kids' TV, TV Comedies","Originally polar opposites, an American fashio..."
4323,s4324,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,"March 1, 2017",2015,NaN,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."
4365,s4366,Movie,My Way,Antongiulio Panizzi,"Silvio Berlusconi, Alan Friedman",Italy,"November 8, 2016",2016,TV-14,101 min,"Documentaries, International Movies",Former Italian prime minister Silvio Berluscon...
4550,s4551,Movie,Numero Zero. The Roots of Italian Rap,Enrico Bisi,NaN,Italy,"April 15, 2018",2015,TV-MA,91 min,"Documentaries, International Movies, Music & M...","In the '90s, the explosive popularity of hip-h..."
4615,s4616,Movie,On My Skin,Alessio Cremonini,"Alessandro Borghi, Jasmine Trinca, Milvia Mari...",Italy,"September 12, 2018",2018,TV-MA,100 min,"Dramas, International Movies","Arrested in Rome for a drug-related offense, S..."
5234,s5235,Movie,Roberto Saviano: Writing Under Police Protection,Pierfrancesco Diliberto,Pierfrancesco Diliberto,Italy,"May 1, 2018",2016,TV-14,45 min,"Documentaries, International Movies","Italian TV host Pif revisits Roberto Saviano, ..."
5284,s5285,Movie,Rose Island,Sydney Sibilia,"Elio Germano, Matilda De Angelis, Tom Wlaschih...",Italy,"December 9, 2020",2020,TV-14,119 min,"Comedies, Dramas, International Movies",An idealistic engineer builds his own island o...
5320,s5321,Movie,S Is for Stanley,Alex Infascelli,NaN,Italy,"June 15, 2017",2016,TV-MA,82 min,"Documentaries, International Movies",This film examines the complex life of iconic ...
5378,s5379,TV Show,SanPa: Sins of the Savior,Cosima Spender,NaN,Italy,"December 30, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Amidst a heroin crisis, Vincenzo Muccioli care..."
5414,s5415,Movie,Saverio Raimondo: Il Satiro Parlante,Francesco Imperato,Saverio Raimondo,Italy,"May 17, 2019",2019,TV-MA,53 min,Stand-Up Comedy,Italian comic and satirist Saverio Raimondo re...
5659,s5660,Movie,Slam,Andrea Molaioli,"Ludovico Tersigni, Jasmine Trinca, Luca Marine...",Italy,"April 15, 2017",2017,TV-MA,99 min,"Comedies, Dramas, International Movies",Teen father-to-be Sam imagines his future as a...
5867,s5868,TV Show,Suburra: Blood on Rome,NaN,"Alessandro Borghi, Giacomo Ferrara, Eduardo Va...",Italy,"October 30, 2020",2020,TV-MA,3 Seasons,"Crime TV Shows, International TV Shows, TV Dramas","In 2008, a fight over land in a seaside town n..."
5880,s5881,TV Show,Summertime,NaN,"Coco Rebecca Edogamhe, Ludovico Tersigni, Aman...",Italy,"April 29, 2020",2020,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Two young adults from very different backgroun...
6089,s6090,Movie,The App,Elisa Fuksas,"Vincenzo Crea, Jessica Cressy, Greta Scarano, ...",Italy,"December 26, 2019",2019,TV-MA,79 min,"Dramas, Independent Movies, International Movies","While in Rome to shoot his first movie, actor ..."
6119,s6120,Movie,The Beast,Ludovico Di Martino,"Fabrizio Gifuni, Lino Musella, Monica Piseddu,...",Italy,"November 27, 2020",2020,TV-MA,100 min,"Action & Adventure, International Movies","To rescue his daughter, an unstable Special Fo..."
6132,s6133,Movie,The Binding,Domenico de Feudis,"Riccardo Scamarcio, Mía Maestro",Italy,"October 2, 2020",2020,TV-MA,93 min,"Horror Movies, International Movies, Thrillers",While visiting her fiancé's mother in southern...
6594,s6595,Movie,The Life Ahead,Edoardo Ponti,"Sophia Loren, Ibrahima Gueye, Renato Carpentie...",Italy,"November 13, 2020",2020,PG-13,95 min,"Dramas, International Movies",A Holocaust survivor running a daycare busines...
6647,s6648,Movie,The Match,Francesco Carnesecchi,"Francesco Pannofino, Alberto Di Stasio, Gabrie...",Italy,"September 1, 2020",2020,TV-MA,97 min,"Dramas, International Movies, Sports Movies",One football match on a dirt pitch near Rome b...
6694,s6695,Movie,The Music of Silence,Michael Radford,"Toby Sebastian, Luisa Ranieri, Jordi Mollà, An...",Italy,"July 1, 2018",2017,TV-PG,115 min,"Dramas, International Movies, Music & Musicals",Based on the autobiography by tenor Andrea Boc...
6768,s6769,Movie,The Players,Stefano Mordini,"Valerio Mastandrea, Riccardo Scamarcio, Laura ...",Italy,"July 15, 2020",2020,TV-MA,89 min,"Comedies, International Movies","From campy lies to sexy surprises, this collec..."
6868,s6869,Movie,The Sign of Venus,Dino Risi,"Sophia Loren, Franca Valeri, Vittorio De Sica,...",Italy,"November 13, 2020",1955,TV-14,97 min,"Classic Movies, Comedies, Independent Movies","While suitors swoon over her cousin, a single ..."
6939,s6940,TV Show,The Trial,Stefano Lodovichi,"Vittoria Puccini, Francesco Scianna, Camilla F...",Italy,"April 10, 2020",2019,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",The murder of a teen girl impacts a public pro...
7307,s7308,Movie,Ultras,Francesco Lettieri,"Aniello Arena, Antonia Truppo, Ciro Nacca, Sim...",Italy,"March 20, 2020",2020,TV-MA,109 min,"Dramas, International Movies, Sports Movies",An aging soccer fanatic faces down the reality...
7335,s7336,Movie,Under the Riccione Sun,Younuts!,"Cristiano Caccamo, Lorenzo Zurzolo, Ludovica M...",Italy,"July 1, 2020",2020,TV-MA,102 min,"Comedies, International Movies, Romantic Movies","While vacationing on the beaches of Riccione, ..."
7525,s7526,Movie,Welcome Mr. President,Riccardo Milani,"Claudio Bisio, Kasia Smutniak, Beppe Fiorello,...",Italy,"October 1, 2016",2013,TV-MA,99 min,"Comedies, International Movies",When frustrated politicians name a historical ...
7639,s7640,TV Show,Winx Club,NaN,"Liza Jacqueline, Helena Evangeliou, Lisa Ortiz...",Italy,"April 15, 2020",2015,TV-Y7,1 Season,Kids' TV,"In this animated fantasy, a girl named Bloom b..."

In [22]:
computer_date= pd.to_datetime(netflix["date_added"])
computer_date

''' nota em alguns casos posso ter campos a null que podem estar como NaN qu eé o equivalente a NULL,  no caso da coluna de date,  pode preencher com algum valor, 
mas para efeitos de aprendizagem vamos manter na mesma o mesmo campo e vamos criar uma coluna ao lado para que se mantenha a coluna original e a coluna convertida'''

0      2020-08-14
1      2016-12-23
2      2018-12-20
3      2017-11-16
4      2020-01-01
          ...
7782   2020-10-19
7783   2019-03-02
7784   2020-09-25
7785   2020-10-31
7786   2020-03-01
Name: date_added, Length: 7787, dtype: datetime64[ns]

In [24]:
# aquilo que anteriormente era uma coluna convertida,  agora está a ser adiciona ao nosso dataframe
netflix["computer_date"]= pd.to_datetime(netflix["date_added"])
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01

In [25]:
# antes de preencher os null values vamos validar que eles existem

netflix["computer_date"] # total de rows >> 7787

0      2020-08-14
1      2016-12-23
2      2018-12-20
3      2017-11-16
4      2020-01-01
          ...
7782   2020-10-19
7783   2019-03-02
7784   2020-09-25
7785   2020-10-31
7786   2020-03-01
Name: computer_date, Length: 7787, dtype: datetime64[ns]

In [26]:
# com isto podemos ver o total de linhas existentes sem null values e tem um total de >> 7777,  ou seja tem pelo menos 10 rows com null

# dropna >  faz o drop a qualquer NA values
netflix["computer_date"].dropna()

0      2020-08-14
1      2016-12-23
2      2018-12-20
3      2017-11-16
4      2020-01-01
          ...
7782   2020-10-19
7783   2019-03-02
7784   2020-09-25
7785   2020-10-31
7786   2020-03-01
Name: computer_date, Length: 7777, dtype: datetime64[ns]

In [29]:
from datetime import datetime as dt

netflix["computer_date"].fillna(dt(2020,1,1),inplace=True)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01

### split columns

In [31]:
# quero que seja feito split sempre que for encontrado uma ', ' e nisto vai criar um column ao lado

netflix["date_added"].str.split(", ",expand=True)

                 0     1
0        August 14  2020
1      December 23  2016
2      December 20  2018
3      November 16  2017
4        January 1  2020
...            ...   ...
7782    October 19  2020
7783       March 2  2019
7784  September 25  2020
7785    October 31  2020
7786       March 1  2020

[7787 rows x 2 columns]

In [33]:
# aqui estoua usar o dataframe e criar duas colunas ,  1 para ter dadosd e de Dia e mes e a outra coluna para ter dados de ano
netflix[["date part1","date part2"]] = netflix["date_added"].str.split(', ', expand=True)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,date part1,date part2
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,August 14,2020
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,December 23,2016
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,December 20,2018
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,November 16,2017
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,January 1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,October 19,2020
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,March 2,2019
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,September 25,2020
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,October 31,2020
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,March 1,2020

In [36]:
# rename method

netflix.rename(columns={"date part1": "month_day"},  inplace=True)
netflix.rename(columns={"date part2": "Year"},  inplace=True)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,month_day,Year
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,August 14,2020
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,December 23,2016
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,December 20,2018
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,November 16,2017
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,January 1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,October 19,2020
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,March 2,2019
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,September 25,2020
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,October 31,2020
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,March 1,2020

In [38]:
# existem caso onte posso precisar de substituir os NAN para alguma mais significativo

netflix["cast"].fillna(value="no cast", inplace=True)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,month_day,Year
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,August 14,2020
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,December 23,2016
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,December 20,2018
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,November 16,2017
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,January 1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,October 19,2020
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,March 2,2019
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,September 25,2020
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,October 31,2020
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,no cast,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,March 1,2020

### apply a functions to every row

In [39]:
# lambda functions

the_adder = lambda x:x +210101
the_adder(3535)

213636

In [43]:
# aqui eu vou ter os elementos da coluna listed_in numa forma de list,  e se usar o len(),  netse mesmo formato vou saber quantos elementos tem dentro dessa lista
#netflix["genre_count"] = netflix["listed_in"].map(lambda x: x.split(","))

# isto serve para saber o len de elementos dentro de uma lista
netflix["genre_count"] = netflix["listed_in"].map(lambda x: len(x.split(",")))
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,month_day,Year,genre_count
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,August 14,2020,3
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,December 23,2016,2
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,December 20,2018,2
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,November 16,2017,3
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,January 1,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,October 19,2020,2
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,March 2,2019,3
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,September 25,2020,3
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,October 31,2020,2
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,no cast,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,March 1,2020,2

In [45]:
netflix["non_sensational_columns"] = netflix.apply(lambda x: len(x["cast"].split(","))+ len(x["listed_in"].split(",")), axis=1)
netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,month_day,Year,genre_count,non_sensational_columns
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,August 14,2020,3,14
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,December 23,2016,2,8
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,December 20,2018,2,11
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,November 16,2017,3,12
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,January 1,2020,1,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,October 19,2020,2,9
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019-03-02,March 2,2019,3,11
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020-09-25,September 25,2020,3,4
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...,2020-10-31,October 31,2020,2,4
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,no cast,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020-03-01,March 1,2020,2,3

### group by and aggregations

In [47]:
# vamos agrupar por pais e fazer o count por show_id
netflix.groupby("country")["show_id"].count()

# podemos ainda melhorar o formato dos daods
netflix.groupby("country")["show_id"].count().reset_index()

                                               country  show_id
0                                            Argentina       50
1    Argentina, Brazil, France, Poland, Germany, De...        1
2                                     Argentina, Chile        1
3                               Argentina, Chile, Peru        1
4                                    Argentina, France        1
..                                                 ...      ...
676                                          Venezuela        1
677                                Venezuela, Colombia        1
678                                            Vietnam        5
679                                       West Germany        1
680                                           Zimbabwe        1

[681 rows x 2 columns]

In [48]:
# criar um varaivel apenas para ter sort dos paises com mais shoes no netflix
netflix_movies_by_country = netflix.groupby("country")["show_id"].count().reset_index()
# com base na variavel que criamos anteriormente vamos apenas,  usar um sort_values indicar qual é a coluna que vai basear o nosso sort // por default o sort é sempre ascending
# neste caso queremos ver os paises que tem o maior numero de shows
netflix_movies_by_country.sort_values(by="show_id", ascending=False)

                               country  show_id
549                      United States     2555
229                              India      923
462                     United Kingdom      397
291                              Japan      226
394                        South Korea      183
..                                 ...      ...
252  Indonesia, South Korea, Singapore        1
253          Indonesia, United Kingdom        1
254           Indonesia, United States        1
255                       Iran, France        1
680                           Zimbabwe        1

[681 rows x 2 columns]

In [50]:
# a mesma linha cell anterior posso colocar tudo na mesma linha se quiser e temos o mesmo output,  apenas tenho de chamar pela variabel.

# o pandas permite que consigamos usar mais do que um method seguido,  isto é bom se pensarmos numa prespectiva de transformaçao
netflix_movies_by_country = netflix.groupby("country")["show_id"].count().reset_index().sort_values(by="show_id", ascending=False)
netflix_movies_by_country

                               country  show_id
549                      United States     2555
229                              India      923
462                     United Kingdom      397
291                              Japan      226
394                        South Korea      183
..                                 ...      ...
252  Indonesia, South Korea, Singapore        1
253          Indonesia, United Kingdom        1
254           Indonesia, United States        1
255                       Iran, France        1
680                           Zimbabwe        1

[681 rows x 2 columns]

### joins and unions

In [51]:
second_dataset = pd.read_csv(pwd +"/netflix_titles_second.csv")
second_dataset

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,23-Dec-16,2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,20-Dec-18,2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,16-Nov-17,2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,1-Jan-20,2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...
349,s350,TV Show,Ainori Love Wagon: Asian Journey,NaN,"Becky, Audrey, Mayuko Kawakita, Shimon Okura",Japan,28-Mar-19,2018,TV-MA,2 Seasons,"International TV Shows, Reality TV, Romantic T...",Seven men and women board a pink bus in search...
350,s351,TV Show,Ainsley Eats the Streets,NaN,Ainsley Harriott,United Kingdom,12-Jul-19,2014,TV-PG,1 Season,"British TV Shows, Docuseries, International TV...",Celebrity chef Ainsley Harriott embarks on a j...
351,s352,Movie,Ainu Mosir,Takeshi Fukunaga,"Kanto Shimokura, Debo Akibe, Emi Shimokura, To...","United States, Japan",17-Nov-20,2020,TV-PG,84 min,"Dramas, International Movies",A sensitive Ainu teen searches for a spiritual...
352,s353,Movie,Airplane Mode,César Rodrigues,"Larissa Manoela, André Luiz Frambach, Erasmo C...",United States,23-Jan-20,2020,TV-PG,97 min,"Comedies, International Movies, Romantic Movies","When Ana, an influencer, crashes her car while..."
353,s354,Movie,Aisa Yeh Jahaan,Biswajeet Bora,"Palash Sen, Ira Dubey, Yashpal Sharma, Tinnu A...",India,15-Oct-17,2015,TV-14,127 min,"Dramas, Independent Movies, International Movies","During a vacation with her parents, away from ..."

In [52]:
#aqui fazemos a concatenação ou nesta casoa o union entre os 2 dataset que tivemos  trablhar anteriormente
new_dataset = pd.concat([netflix,second_dataset ])
new_dataset

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,month_day,Year,genre_count,non_sensational_columns
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,August 14,2020,3.0,14.0
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...,2016-12-23,December 23,2016,2.0,8.0
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow...",2018-12-20,December 20,2018,2.0,11.0
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16,November 16,2017,3.0,12.0
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01,January 1,2020,1.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,s350,TV Show,Ainori Love Wagon: Asian Journey,NaN,"Becky, Audrey, Mayuko Kawakita, Shimon Okura",Japan,28-Mar-19,2018,TV-MA,2 Seasons,"International TV Shows, Reality TV, Romantic T...",Seven men and women board a pink bus in search...,NaT,NaN,NaN,NaN,NaN
350,s351,TV Show,Ainsley Eats the Streets,NaN,Ainsley Harriott,United Kingdom,12-Jul-19,2014,TV-PG,1 Season,"British TV Shows, Docuseries, International TV...",Celebrity chef Ainsley Harriott embarks on a j...,NaT,NaN,NaN,NaN,NaN
351,s352,Movie,Ainu Mosir,Takeshi Fukunaga,"Kanto Shimokura, Debo Akibe, Emi Shimokura, To...","United States, Japan",17-Nov-20,2020,TV-PG,84 min,"Dramas, International Movies",A sensitive Ainu teen searches for a spiritual...,NaT,NaN,NaN,NaN,NaN
352,s353,Movie,Airplane Mode,César Rodrigues,"Larissa Manoela, André Luiz Frambach, Erasmo C...",United States,23-Jan-20,2020,TV-PG,97 min,"Comedies, International Movies, Romantic Movies","When Ana, an influencer, crashes her car while...",NaT,NaN,NaN,NaN,NaN
353,s354,Movie,Aisa Yeh Jahaan,Biswajeet Bora,"Palash Sen, Ira Dubey, Yashpal Sharma, Tinnu A...",India,15-Oct-17,2015,TV-14,127 min,"Dramas, Independent Movies, International Movies","During a vacation with her parents, away from ...",NaT,NaN,NaN,NaN,NaN

### pivot and melt

In [55]:
'''
este pode ser perfeitamente o standard para abordar os jois de 2 dataframes

netflix_merged = pd.merge(left=, right=,  how=, left_on=,right_om= )

vamos ter de ter 2 dataset:
> new_dataset
> netflix_movies_by_country
> vamos fazer um inner join
> depois indicar qual o campo que vamos fazer o join
'''

netflix_merged = pd.merge(left=new_dataset, right=netflix_movies_by_country,  how="inner", left_on=["country"],right_on=["country"])
netflix_merged

,show_id_x,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,computer_date,month_day,Year,genre_count,non_sensational_columns,show_id_y
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14,August 14,2020,3.0,14.0,72
1,s209,Movie,A new Capitalism,NaN,no cast,Brazil,"June 12, 2018",2017,TV-14,76 min,"Documentaries, International Movies",Entrepreneurs worldwide explore alternatives t...,2018-06-12,June 12,2018,2.0,3.0,72
2,s219,TV Show,A Queen Is Born,Carla Barros,"Gloria Groove, Alexia Twister",Brazil,"November 11, 2020",2020,TV-14,1 Season,"International TV Shows, Reality TV",Gloria Groove and Alexia Twister make drag dre...,2020-11-11,November 11,2020,2.0,4.0,72
3,s321,Movie,Afonso Padilha: Classless,"Junior Carelli, Rudge Campos",Afonso Padilha,Brazil,"September 3, 2020",2020,TV-MA,63 min,Stand-Up Comedy,Brazilian comedian Afonso Padilha dives into h...,2020-09-03,September 3,2020,1.0,2.0,72
4,s323,TV Show,Afronta! Facing It!,Juliana Vicente,"Loo Nascimento, Ingrid Silva, Rincon Sapiência...",Brazil,"October 31, 2020",2017,TV-PG,1 Season,"Docuseries, International TV Shows",This docuseries spotlights Afro-Brazilian thin...,2020-10-31,October 31,2020,2.0,28.0,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7618,s7727,Movie,You Carry Me,Ivona Juka,"Lana Baric, Vojislav Brajovic, Natasa Janjic, ...","Croatia, Slovenia, Serbia, Montenegro","July 1, 2016",2015,TV-MA,157 min,"Dramas, International Movies","A soap opera producer, director and makeup art...",2016-07-01,July 1,2016,2.0,12.0,1
7619,s7751,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...,2018-05-01,May 1,2018,2.0,7.0,1
7620,s7760,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...,2018-09-13,September 13,2018,1.0,8.0,1
7621,s7771,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...,2016-03-09,March 9,2016,3.0,9.0,1
7622,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020-10-19,October 19,2020,2.0,9.0,1

In [56]:
# pivot a table

'''
> index,  é o ponto de valiçao quero ver por paises
> quero que a colunas sejam todos os elementos que estejam presentes em type (se é um movie ou um tv show)
> quero se conte o numero de titles por type,  isto vai fazer um count,  com base nos countries

> depois do count temos,  fill_value=0 , que é basicamente qualquer paises que nao tenha um match ou umcount nestes 2 types apresenta 0

nota:  sempre que precisamos de dar um limpeza nos dados,  usamos sempre no fim .reset_index()

'''


pivot_table = netflix.pivot_table(index="country",  columns="type", values = "title", aggfunc="count", fill_value=0).reset_index()
pivot_table

type                                            country  Movie  TV Show
0                                             Argentina     34       16
1     Argentina, Brazil, France, Poland, Germany, De...      1        0
2                                      Argentina, Chile      1        0
3                                Argentina, Chile, Peru      1        0
4                                     Argentina, France      1        0
..                                                  ...    ...      ...
676                                           Venezuela      1        0
677                                 Venezuela, Colombia      1        0
678                                             Vietnam      5        0
679                                        West Germany      1        0
680                                            Zimbabwe      1        0

[681 rows x 3 columns]

In [57]:
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                   'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})

df

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [58]:
df.melt(id_vars=['A'], value_vars=['B'],
        var_name='myVarname', value_name='myValname')

   A myVarname  myValname
0  a         B          1
1  b         B          3
2  c         B          5